In [1]:
import pathlib
from fastai.text import *
from data import *
from model import MultiLinearDecoder
from loss import annotation_loss
import pickle
from sklearn.model_selection import train_test_split
%reload_ext autoreload
%autoreload 2

/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using TensorFlow backend.


In [2]:
directory = pathlib.Path('/data/fakenews/tasks-2-3/train/')
ids, texts, labels = read_data(directory)

In [3]:
len(labels)

293

In [4]:
ids_train, ids_valid, texts_train, texts_valid, labels_train, labels_valid = train_test_split(ids,texts,labels,test_size=0.15, random_state=42)

In [5]:
vocab = Vocab(pickle.load(open('/data/fakenews/itos_wt103.pkl','rb')))
train = PropagandaDataset(ids_train, texts_train, labels_train, vocab)
valid = PropagandaDataset(ids_valid, texts_valid, labels_valid, vocab)
logging.info("Dataset Created")

Marking  but as 16
Marking  scientists as 16
Marking  are as 16
Marking  n’t as 16
Marking  worried as 16
Marking  researchers as 0
Marking  say as 0
Marking  it as 0
Marking  will as 0
Marking  have as 0
Marking  very as 0
Marking  little as 0
Marking  effect as 0
Marking  on as 0
Marking  the as 0
Marking  overall as 0
Marking  global as 0
Marking  warming as 0
Marking  trend as 0
Marking  that as 0
Marking  mankind as 0
Marking  has as 0
Marking  created as 0
Marking  for as 0
Marking  itself as 0
Marking  . as 0
Marking  

 as 0
Marking  obama as 9
Marking  's as 9
Marking  victims as 9
Marking  very as 8
Marking  deliberately as 8
Marking  ridiculing as 8
Marking  shrugging as 6
Marking  at as 6
Marking  the as 6
Marking  murder as 6
Marking  completely as 6
Marking  collapsed as 6
Marking  because as 4
Marking  it as 4
Marking  would as 4
Marking  have as 4
Marking  been as 4
Marking  damaging as 4
Marking  to as 4
Marking  obama as 4
Marking  shock as 8
Marking  grossly as 8
Mar

Marking  the as 8
Marking  death as 8
Marking  penalty as 8
Marking  without as 4
Marking  the as 4
Marking  shedding as 4
Marking  of as 4
Marking  blood as 4
Marking  there as 4
Marking  is as 4
Marking  no as 4
Marking  remission as 4
Marking  eternal as 8
Marking  bliss as 8
Marking  in as 8
Marking  heaven as 8
Marking  one as 6
Marking  of as 6
Marking  the as 6
Marking  cruelest as 6
Marking  means as 6
Marking  ever as 6
Marking  devised as 6
Marking  a as 6
Marking  miscarriage as 6
Marking  of as 6
Marking  human as 6
Marking  justice as 6
Marking  beyond as 6
Marking  any as 6
Marking  the as 6
Marking  world as 6
Marking  could as 6
Marking  ever as 6
Marking  have as 6
Marking  imagined as 6
Marking  the as 9
Marking  glorified as 9
Marking  man as 9
Marking  who as 9
Marking  is as 9
Marking  christ as 9
Marking  the as 9
Marking  king as 9
Marking  from as 4
Marking  that as 4
Marking  point as 4
Marking  on as 4
Marking  it as 4
Marking  is as 4
Marking  christ as 4
Mar

Marking  ” as 9
Marking  tired as 8
Marking  farce as 8
Marking  hit as 8
Marking  the as 15
Marking  authorities as 15
Marking  allowed as 15
Marking  him as 15
Marking  to as 15
Marking  commit as 15
Marking  the as 15
Marking  crime as 15
Marking  . as 15
Marking  hit as 8
Marking  her as 8
Marking  mercilessly as 8
Marking  “ as 13
Marking  a as 13
Marking  satan as 13
Marking  ” as 13
Marking  crazy as 8
Marking  crazy as 8
Marking  treason as 8
Marking  even as 6
Marking  worse as 6
Marking  even as 6
Marking  worse as 6
Marking  treason as 13
Marking  treason as 13
Marking  for as 6
Marking  years as 6
Marking  , as 6
Marking  and as 6
Marking  probably as 6
Marking  decades as 6
Marking  the as 6
Marking  worst as 6
Marking  blind as 9
Marking  to as 9
Marking  corruption as 9
Marking  black as 9
Marking  - as 9
Marking  hearted as 9
Marking  presbyterian as 9
Marking  bigot as 9
Marking  crook as 9
Marking  and as 9
Marking  an as 9
Marking  economic as 9
Marking  leftist as 9

Marking  there as 16
Marking  . as 16
Marking  ” as 16
Marking  
 as 16
Marking  the as 10
Marking  cardinal as 10
Marking  ’s as 10
Marking  office as 10
Marking  maintains as 10
Marking  that as 10
Marking  rather as 10
Marking  than as 10
Marking  saying as 10
Marking  “ as 10
Marking  yes as 10
Marking  , as 10
Marking  ” as 10
Marking  there as 10
Marking  is as 10
Marking  a as 10
Marking  possibility as 10
Marking  of as 10
Marking  liturgical as 10
Marking  “ as 10
Marking  blessing as 10
Marking  ” as 10
Marking  of as 10
Marking  gay as 10
Marking  unions as 10
Marking  , as 10
Marking  he as 10
Marking  answered as 10
Marking  the as 10
Marking  question as 10
Marking  in as 10
Marking  a as 10
Marking  more as 10
Marking  subtle as 10
Marking  way as 10
Marking  without as 10
Marking  giving as 10
Marking  an as 10
Marking  explicit as 10
Marking  “ as 10
Marking  yes as 10
Marking  . as 10
Marking  ” as 10
Marking  there as 10
Marking  are as 10
Marking  no as 10
Marking  

Marking  talented as 6
Marking  , as 6
Marking  more as 6
Marking  dedicated as 6
Marking  group as 6
Marking  of as 6
Marking  law as 6
Marking  enforcement as 6
Marking  investigators as 6
Marking  and as 6
Marking  prosecutors as 6
Marking  than as 6
Marking  the as 6
Marking  united as 6
Marking  states as 6
Marking  nearly as 6
Marking  constant as 6
Marking  complaints as 6
Marking  from as 6
Marking  trump as 6
Marking  the as 6
Marking  deadliest as 6
Marking  mass as 6
Marking  shooting as 6
Marking  in as 6
Marking  modern as 6
Marking  u.s. as 6
Marking  history as 6
Marking  meaning as 5
Marking  he as 5
Marking  has as 5
Marking  n’t as 5
Marking  bothered as 5
Marking  to as 5
Marking  do as 5
Marking  any as 5
Marking  serious as 5
Marking  investigation as 5
Marking  beyond as 5
Marking  a as 5
Marking  few as 5
Marking  google as 5
Marking  searches as 5
Marking  . as 5
Marking  
 as 5
Marking  innovators as 8
Marking  who as 8
Marking  wish as 8
Marking  to as 8
Marki

Marking  hamas as 2
Marking  a as 2
Marking  terrorist as 2
Marking  group as 2
Marking  . as 2
Marking  
 as 2
Marking  time as 2
Marking  for as 2
Marking  us as 2
Marking  to as 2
Marking  do as 2
Marking  same as 2
Marking  . as 2
Marking  " as 2
Marking  anti as 13
Marking  - as 13
Marking  israel as 13
Marking  any as 1
Marking  jew as 1
Marking  who as 1
Marking  opposes as 1
Marking  the as 1
Marking  occupation as 1
Marking  — as 1
Marking  or as 1
Marking  opposes as 1
Marking  zionism as 1
Marking  itself as 1
Marking  — as 1
Marking  knows as 1
Marking  that as 1
Marking  feeling as 1
Marking  of as 1
Marking  being as 1
Marking  shunned as 1
Marking  from as 1
Marking  the as 1
Marking  places as 1
Marking  that as 1
Marking  are as 1
Marking  supposed as 1
Marking  to as 1
Marking  shelter as 1
Marking  and as 1
Marking  nurture as 1
Marking  you as 1
Marking  : as 1
Marking  families as 1
Marking  , as 1
Marking  synagogues as 1
Marking  , as 1
Marking  community as 1
Ma

Marking  movement as 9
Marking  i as 4
Marking  have as 4
Marking  no as 4
Marking  doubt as 4
Marking  from as 4
Marking  the as 4
Marking  information as 4
Marking  circulated as 4
Marking  about as 4
Marking  me as 4
Marking  and as 4
Marking  campaign as 4
Marking  run as 4
Marking  against as 4
Marking  me as 4
Marking  prior as 4
Marking  to as 4
Marking  this as 4
Marking  vote as 4
Marking  that as 4
Marking  this as 4
Marking  was as 4
Marking  about as 4
Marking  my as 4
Marking  jewish as 4
Marking  identity as 4
Marking  , as 4
Marking  and as 4
Marking  nothing as 4
Marking  more as 4
Marking  why as 5
Marking  did as 5
Marking  a as 5
Marking  bds as 5
Marking  - as 5
Marking  led as 5
Marking  campaign as 5
Marking  name as 5
Marking  and as 5
Marking  shame as 5
Marking  me as 5
Marking  for as 5
Marking  my as 5
Marking  affiliation as 5
Marking  with as 5
Marking  a as 5
Marking  jewish as 5
Marking  organization as 5
Marking  , as 5
Marking  and as 5
Marking  call as

Marking  are as 6
Marking  nothing as 6
Marking  more as 6
Marking  than as 6
Marking  a as 6
Marking  handful as 6
Marking  of as 6
Marking  people as 6
Marking  enslaved as 8
Marking  authoritarian as 8
Marking  wreak as 8
Marking  havoc as 8
Marking  our as 7
Marking  society as 7
Marking  absolute as 8
Marking  horror as 8
Marking  the as 13
Marking  invasion as 13
Marking  of as 13
Marking  muslims as 13
Marking  migrant as 13
Marking  invasion as 13
Marking  . as 13
Marking  “ as 7
Marking  christianity as 7
Marking  is as 7
Marking  europe as 7
Marking  ’s as 7
Marking  last as 7
Marking  hope as 7
Marking  . as 7
Marking  ” as 7
Marking  “ as 14
Marking  christianity as 14
Marking  is as 14
Marking  europe as 14
Marking  ’s as 14
Marking  last as 14
Marking  hope as 14
Marking  . as 14
Marking  ” as 14
Marking  
 as 14
Marking  “ as 1
Marking  our as 1
Marking  worst as 1
Marking  nightmares as 1
Marking  can as 1
Marking  come as 1
Marking  true as 1
Marking  . as 1
Marking  


Marking  blackmail as 5
Marking  and as 5
Marking  god as 5
Marking  knows as 5
Marking  what as 5
Marking  else as 5
Marking  ? as 5
Marking  
 as 5
Marking  and as 5
Marking  how as 5
Marking  deeply as 5
Marking  has as 5
Marking  america as 5
Marking  been as 5
Marking  compromised as 5
Marking  god as 8
Marking  knows as 8
Marking  what as 8
Marking  else as 8
Marking  how as 7
Marking  deeply as 7
Marking  has as 7
Marking  america as 7
Marking  been as 7
Marking  compromised as 7
Marking  vanished as 8
Marking  the as 9
Marking  house as 9
Marking  ’s as 9
Marking  top as 9
Marking  cop as 9
Marking  becerra as 5
Marking  — as 5
Marking  now as 5
Marking  california as 5
Marking  ’s as 5
Marking  democratic as 5
Marking  attorney as 5
Marking  general as 5
Marking  — as 5
Marking  failed as 5
Marking  to as 5
Marking  ensure as 5
Marking  that as 5
Marking  the as 5
Marking  awans as 5
Marking  did as 5
Marking  n’t as 5
Marking  have as 5
Marking  access as 5
Marking  to as 5
M

Marking  , as 5
Marking  and as 5
Marking  yet as 5
Marking  know as 5
Marking  nothing as 5
Marking  of as 5
Marking  it as 5
Marking  ( as 5
Marking  1 as 5
Marking  john as 5
Marking  3:18 as 5
Marking  ) as 5
Marking  . as 5
Marking  
 as 5
Marking  they as 5
Marking  read as 5
Marking  what as 5
Marking  to as 5
Marking  do as 5
Marking  , as 5
Marking  but as 5
Marking  do as 5
Marking  it as 5
Marking  not as 5
Marking  ! as 5
Marking  
 as 5
Marking  in as 5
Marking  fact as 5
Marking  , as 5
Marking  they as 5
Marking  declare as 5
Marking  and as 5
Marking  proclaim as 5
Marking  how as 5
Marking  much as 5
Marking  they as 5
Marking  love as 5
Marking  god as 5
Marking  , as 5
Marking  and as 5
Marking  yet as 5
Marking  if as 5
Marking  you as 5
Marking  were as 5
Marking  to as 5
Marking  have as 5
Marking  them as 5
Marking  read as 5
Marking  his as 5
Marking  moral as 5
Marking  law as 5
Marking  and as 5
Marking  look as 5
Marking  to as 5
Marking  their as 5
Marking  

Marking  get as 8
Marking  their as 8
Marking  hands as 8
Marking  on as 8
Marking  him as 8
Marking  all as 4
Marking  for as 4
Marking  spreading as 4
Marking  unwelcome as 4
Marking  truth as 4
Marking  around as 4
Marking  one as 5
Marking  might as 5
Marking  ask as 5
Marking  , as 5
Marking  is as 5
Marking  “ as 5
Marking  unseemly as 5
Marking  sycophancy as 5
Marking  ” as 5
Marking  at as 5
Marking  work as 5
Marking  among as 5
Marking  the as 5
Marking  media as 5
Marking  unseemly as 8
Marking  sycophancy as 8
Marking  the as 9
Marking  noble as 9
Marking  profession as 9
Marking  of as 9
Marking  journalism as 9
Marking  deafening as 8
Marking  vichy as 9
Marking  journalists as 9
Marking  after as 12
Marking  the as 12
Marking  vichy as 12
Marking  government as 12
Marking  that as 12
Marking  served as 12
Marking  ad as 12
Marking  enabled as 12
Marking  the as 12
Marking  german as 12
Marking  occupation as 12
Marking  of as 12
Marking  france as 12
Marking  no as 6
Ma

Marking  course as 4
Marking  , as 4
Marking  resign as 4
Marking  . as 4
Marking  
 as 4
Marking  he as 4
Marking  will as 4
Marking  cling as 4
Marking  to as 4
Marking  power as 4
Marking  with as 4
Marking  his as 4
Marking  last as 4
Marking  breath as 4
Marking  in as 4
Marking  order as 4
Marking  to as 4
Marking  carry as 4
Marking  out as 4
Marking  the as 4
Marking  many as 4
Marking  other as 4
Marking  acts as 4
Marking  of as 4
Marking  ecclesial as 4
Marking  subversion as 4
Marking  he as 4
Marking  clearly as 4
Marking  has as 4
Marking  in as 4
Marking  mind as 4
Marking  the as 8
Marking  plague as 8
Marking  of as 8
Marking  bergoglio as 8
Marking  the as 9
Marking  execrable as 9
Marking  benedict as 9
Marking  ix as 9
Marking  the as 9
Marking  interloper as 9
Marking  sylvester as 9
Marking  iii as 9
Marking  the as 9
Marking  well as 9
Marking  - as 9
Marking  intentioned as 9
Marking  but as 9
Marking  dimwitted as 9
Marking  gregory as 9
Marking  vi as 9
Markin

Marking  botched as 8
Marking  elections as 8
Marking  , as 8
Marking  legal as 8
Marking  disputes as 8
Marking  and as 8
Marking  blistering as 8
Marking  criticism as 8
Marking  passion as 8
Marking  and as 8
Marking  honor as 8
Marking  by as 16
Marking  the as 16
Marking  way as 16
Marking  she as 6
Marking  should as 6
Marking  be as 6
Marking  ready as 6
Marking  for as 6
Marking  prison as 6
Marking  bars as 6
Marking  after as 6
Marking  the as 6
Marking  fiasco as 6
Marking  she as 6
Marking  has as 6
Marking  created as 6
Marking  fiasco as 8
Marking  a as 7
Marking  county as 7
Marking  whose as 7
Marking  supervisor as 7
Marking  of as 7
Marking  elections as 7
Marking  has as 7
Marking  a as 7
Marking  history as 7
Marking  of as 7
Marking  losing as 7
Marking  ballots as 7
Marking  and as 7
Marking  breaking as 7
Marking  laws as 7
Marking  by as 7
Marking  allowing as 7
Marking  illegal as 7
Marking  immigrants as 7
Marking  and as 7
Marking  felons as 7
Marking  to as 

Marking  death as 8
Marking  , as 8
Marking  this as 1
Marking  is as 1
Marking  a as 1
Marking  matter as 1
Marking  of as 1
Marking  life as 1
Marking  and as 1
Marking  death as 1
Marking  , as 1
Marking  and as 1
Marking  any as 1
Marking  complacency as 1
Marking  towards as 1
Marking  islam as 1
Marking  is as 1
Marking  treasonous as 1
Marking  . as 1
Marking  
 as 1
Marking  we as 1
Marking  do as 1
Marking  not as 1
Marking  wish as 1
Marking  the as 1
Marking  west as 1
Marking  to as 1
Marking  continue as 1
Marking  with as 1
Marking  islamization as 1
Marking  , as 1
Marking  nor as 1
Marking  that as 1
Marking  your as 1
Marking  actions as 1
Marking  contribute as 1
Marking  to as 1
Marking  it as 1
Marking  . as 1
Marking  best as 6
Marking  - as 6
Marking  ever as 6
Marking  great as 9
Marking  white as 9
Marking  father as 9
Marking  delinquent as 9
Marking  ‘ as 9
Marking  little as 9
Marking  rocket as 9
Marking  man’ as 9
Marking  ‘ as 9
Marking  dotard’ as 9
Marki

Marking  correction as 6
Marking  manoeuvre as 6
Marking  ever as 6
Marking  the as 6
Marking  farthest as 6
Marking  planetary as 6
Marking  encounter as 6
Marking  in as 6
Marking  history as 6
Marking  the as 6
Marking  next as 6
Marking  record as 6
Marking  - as 6
Marking  breaking as 6
Marking  encounter as 6
Marking  record as 13
Marking  - as 13
Marking  breaking as 13
Marking  record as 8
Marking  - as 8
Marking  breaking as 8
Marking  it as 8
Marking  is as 8
Marking  high as 8
Marking  time as 8
Marking  on as 6
Marking  a as 6
Marking  massive as 6
Marking  scale as 6
Marking  massive as 8
Marking  a as 9
Marking  pro as 9
Marking  - as 9
Marking  jihad as 9
Marking  marxist as 9
Marking  democrat as 9
Marking  the as 7
Marking  democrats as 7
Marking  are as 7
Marking  likewise as 7
Marking  working as 7
Marking  feverishly as 7
Marking  to as 7
Marking  overturn as 7
Marking  the as 7
Marking  will as 7
Marking  of as 7
Marking  the as 7
Marking  people as 7
Marking  they

Marking  or as 3
Marking  hell as 3
Marking  ? as 3
Marking  pretty as 8
Marking  clear as 8
Marking  foundation as 8
Marking  of as 8
Marking  lies as 8
Marking  you as 9
Marking  are as 9
Marking  not as 9
Marking  a as 9
Marking  christian as 9
Marking  
 as 11
Marking  ( as 11
Marking  faber as 11
Marking  was as 11
Marking  nominated as 11
Marking  by as 11
Marking  president as 11
Marking  george as 11
Marking  h.w. as 11
Marking  
 as 11
Marking  bush as 11
Marking  . as 11
Marking  ) as 11
Marking  

 as 11
Marking  very as 8
Marking  , as 8
Marking  very as 8
Marking  extremely as 8
Marking  liberty as 14
Marking  of as 14
Marking  conscience as 14
Marking  is as 14
Marking  not as 14
Marking  up as 14
Marking  for as 14
Marking  a as 14
Marking  vote as 14
Marking  say as 8
Marking  , as 8
Marking  ‘ as 8
Marking  hola’ as 8
Marking  to as 8
Marking  trump as 8
Marking  ’s as 8
Marking  razor as 8
Marking  wire as 8
Marking  migrants as 8
Marking  taunting as 8
Marking  secur

Marking  did as 4
Marking  n’t as 4
Marking  want as 4
Marking  to as 4
Marking  have as 4
Marking  a as 4
Marking  rational as 4
Marking  discussion as 4
Marking  as as 8
Marking  weak as 8
Marking  and as 8
Marking  ridiculous as 8
Marking  as as 8
Marking  they as 8
Marking  are as 8
Marking  hurl as 8
Marking  the as 8
Marking  wild as 8
Marking  claims as 8
Marking  like as 8
Marking  a as 8
Marking  grenade as 8
Marking  lawyers as 9
Marking  are as 9
Marking  masters as 9
Marking  of as 9
Marking  delay as 9
Marking  social as 9
Marking  justice as 9
Marking  warrior as 9
Marking  - as 9
Marking  lawyers as 9
Marking  hoping as 8
Marking  to as 8
Marking  torpedo as 8
Marking  president as 8
Marking  trump as 8
Marking  ’s as 8
Marking  agenda as 8
Marking  a as 9
Marking  staunch as 9
Marking  conservative as 9
Marking  left as 9
Marking  - as 9
Marking  wingers as 9
Marking  utter as 8
Marking  nonsense as 8
Marking  she as 5
Marking  is as 5
Marking  going as 5
Marking  to as

Marking  , as 0
Marking  so as 0
Marking  that as 0
Marking  islam as 0
Marking  and as 0
Marking  its as 0
Marking  people as 0
Marking  may as 0
Marking  be as 0
Marking  exalted as 0
Marking  and as 0
Marking  the as 0
Marking  race as 0
Marking  of as 0
Marking  infidels as 0
Marking  brought as 0
Marking  low as 0
Marking  . as 0
Marking  
 as 0
Marking  the as 0
Marking  jizya as 0
Marking  is as 0
Marking  to as 0
Marking  be as 0
Marking  imposed as 0
Marking  on as 0
Marking  all as 0
Marking  of as 0
Marking  them as 0
Marking  in as 0
Marking  full as 0
Marking  , as 0
Marking  without as 0
Marking  exception as 0
Marking  the as 9
Marking  infidels as 9
Marking  and as 4
Marking  the as 4
Marking  imposition as 4
Marking  of as 4
Marking  their as 4
Marking  poll as 4
Marking  tax as 4
Marking  [ as 4
Marking  jizya as 4
Marking  ] as 4
Marking  , as 4
Marking  “ as 4
Marking  until as 4
Marking  they as 4
Marking  pay as 4
Marking  the as 4
Marking  tribute as 4
Marking  o

Marking  july as 5
Marking  when as 5
Marking  she as 5
Marking  first as 5
Marking  received as 5
Marking  word as 5
Marking  of as 5
Marking  the as 5
Marking  allegation as 5
Marking  this as 4
Marking  is as 4
Marking  all as 4
Marking  a as 4
Marking  ruse as 4
Marking  to as 4
Marking  block as 4
Marking  judge as 4
Marking  kavanaugh as 4
Marking  's as 4
Marking  confirmation as 4
Marking  by as 4
Marking  all as 4
Marking  means as 4
Marking  necessary as 4
Marking  slink as 8
Marking  back as 8
Marking  into as 8
Marking  their as 8
Marking  shadowy as 8
Marking  corner as 8
Marking  massacre as 8
Marking  not as 5
Marking  only as 5
Marking  did as 5
Marking  the as 5
Marking  coroner as 5
Marking  drag as 5
Marking  his as 5
Marking  feet as 5
Marking  and as 5
Marking  release as 5
Marking  the as 5
Marking  autopsy as 5
Marking  reports as 5
Marking  late as 5
Marking  wednesday as 5
Marking  , as 5
Marking  but as 5
Marking  all as 5
Marking  of as 5
Marking  the as 5
Ma

Marking  neo as 9
Marking  - as 9
Marking  catholic as 9
Marking  apologists as 9
Marking  yet as 5
Marking  there as 5
Marking  is as 5
Marking  little as 5
Marking  doubt as 5
Marking  they as 5
Marking  will as 5
Marking  continue as 5
Marking  the as 5
Marking  same as 5
Marking  polemic as 5
Marking  that as 5
Marking  for as 5
Marking  nearly as 5
Marking  sixty as 5
Marking  years as 5
Marking  has as 5
Marking  doggedly as 5
Marking  defended as 5
Marking  every as 5
Marking  one as 5
Marking  of as 5
Marking  the as 5
Marking  ruinous as 5
Marking  “ as 5
Marking  reforms as 5
Marking  ” as 5
Marking  that as 5
Marking  have as 5
Marking  resulted as 5
Marking  in as 5
Marking  a as 5
Marking  debacle as 5
Marking  without as 5
Marking  equal as 5
Marking  in as 5
Marking  church as 5
Marking  history as 5
Marking  the as 8
Marking  ruinous as 8
Marking  “ as 8
Marking  reforms as 8
Marking  debacle as 6
Marking  without as 6
Marking  equal as 6
Marking  in as 6
Marking  churc

Marking  end as 8
Marking  bergoglio as 9
Marking  ’s as 9
Marking  “ as 9
Marking  trusted as 9
Marking  counselor as 9
Marking  united as 8
Marking  by as 8
Marking  a as 8
Marking  wicked as 8
Marking  pact as 8
Marking  of as 8
Marking  abuses as 8
Marking  by as 8
Marking  the as 8
Marking  first as 8
Marking  , as 8
Marking  and as 8
Marking  at as 8
Marking  least as 8
Marking  of as 8
Marking  coverup as 8
Marking  of as 8
Marking  abuses as 8
Marking  by as 8
Marking  the as 8
Marking  other as 8
Marking  two as 8
Marking  the as 9
Marking  obscure as 9
Marking  bishop as 9
Marking  of as 9
Marking  rapid as 9
Marking  city as 9
Marking  accelerated as 8
Marking  degeneration as 8
Marking  he as 5
Marking  is as 5
Marking  the as 5
Marking  very as 5
Marking  exemplar as 5
Marking  of as 5
Marking  the as 5
Marking  crisis as 5
Marking  we as 5
Marking  must as 5
Marking  still as 5
Marking  endure as 5
Marking  the as 9
Marking  2002 as 9
Marking  “ as 9
Marking  pedophile as

Marking  pope as 5
Marking  benedict as 5
Marking  , as 5
Marking  how as 5
Marking  can as 5
Marking  his as 5
Marking  answer as 5
Marking  be as 5
Marking  explained as 5
Marking  absolutely as 8
Marking  laughable as 8
Marking  lies as 8
Marking  shamelessly as 8
Marking  however as 5
Marking  , as 5
Marking  he as 5
Marking  failed as 5
Marking  to as 5
Marking  acknowledge as 5
Marking  receipt as 5
Marking  of as 5
Marking  my as 5
Marking  two as 5
Marking  letters as 5
Marking  , as 5
Marking  contrary as 5
Marking  to as 5
Marking  what as 5
Marking  he as 5
Marking  customarily as 5
Marking  did as 5
Marking  he as 5
Marking  put as 5
Marking  other as 5
Marking  seminarians as 5
Marking  at as 5
Marking  risk as 5
Marking  better as 6
Marking  a as 6
Marking  thousand as 6
Marking  septuagenarian as 6
Marking  wuerls as 6
Marking  in as 6
Marking  their as 6
Marking  lavish as 6
Marking  sties as 6
Marking  of as 6
Marking  corruption as 6
Marking  , as 6
Marking  financed 

Marking  bombshell as 8
Marking  a as 9
Marking  “ as 9
Marking  substitute as 9
Marking  of as 9
Marking  our as 9
Marking  lord as 9
Marking  this as 4
Marking  is as 4
Marking  clearly as 4
Marking  the as 4
Marking  testimony as 4
Marking  of as 4
Marking  an as 4
Marking  honest as 4
Marking  man as 4
Marking  who as 4
Marking  has as 4
Marking  only as 4
Marking  the as 4
Marking  good as 4
Marking  of as 4
Marking  the as 4
Marking  church as 4
Marking  in as 4
Marking  his as 4
Marking  heart as 4
Marking  — as 4
Marking  a as 4
Marking  modern as 4
Marking  - as 4
Marking  day as 4
Marking  athanasius as 4
Marking  standing as 4
Marking  against as 4
Marking  something as 4
Marking  so as 4
Marking  much as 4
Marking  worse as 4
Marking  than as 4
Marking  liberius as 4
Marking  an as 9
Marking  honest as 9
Marking  man as 9
Marking  who as 9
Marking  has as 9
Marking  only as 9
Marking  the as 9
Marking  good as 9
Marking  of as 9
Marking  the as 9
Marking  church as 9
Markin

Marking  still as 5
Marking  the as 5
Marking  incompetent as 5
Marking  , as 5
Marking  clueless as 5
Marking  authorities as 5
Marking  know as 5
Marking  nothing as 5
Marking  . as 5
Marking  
 as 5
Marking  incompetent as 9
Marking  , as 9
Marking  clueless as 9
Marking  authorities as 9
Marking  that as 5
Marking  ’s as 5
Marking  the as 5
Marking  information as 5
Marking  they as 5
Marking  seek as 5
Marking  to as 5
Marking  blackout as 5
Marking  . as 5
Marking  botched as 8
Marking  investigation as 8
Marking  this as 7
Marking  is as 7
Marking  not as 7
Marking  the as 7
Marking  soviet as 7
Marking  union as 7
Marking  , as 7
Marking  this as 7
Marking  is as 7
Marking  not as 7
Marking  iran as 7
Marking  or as 7
Marking  riyadh as 7
Marking  – as 7
Marking  this as 7
Marking  is as 7
Marking  america as 7
Marking  . as 7
Marking  
 as 7
Marking  bumbling as 9
Marking  fbi as 9
Marking  local as 5
Marking  and as 5
Marking  federal as 5
Marking  authorities as 5
Marking  a

Marking  like as 8
Marking  it as 8
Marking  ’s as 8
Marking  worth as 8
Marking  a as 8
Marking  good as 8
Marking  deal as 8
Marking  more as 8
Marking  than as 8
Marking  1,000 as 8
Marking  words as 8
Marking  . as 8
Marking  
 as 8
Marking  it as 8
Marking  illuminates as 8
Marking  just as 8
Marking  a as 8
Marking  small as 8
Marking  sliver as 8
Marking  of as 8
Marking  the as 8
Marking  public as 8
Marking  health as 8
Marking  crisis as 8
Marking  devastated as 8
Marking  the as 6
Marking  post as 6
Marking  - as 6
Marking  apocalyptic as 6
Marking  ravaged as 6
Marking  territory as 6
Marking  the as 8
Marking  islands as 8
Marking  are as 8
Marking  grappling as 8
Marking  with as 8
Marking  the as 1
Marking  islands as 1
Marking  are as 1
Marking  grappling as 1
Marking  with as 1
Marking  physician as 1
Marking  shortages as 1
Marking  , as 1
Marking  medicaid as 1
Marking  programs as 1
Marking  facing as 1
Marking  an as 1
Marking  impending as 1
Marking  funding as 1


Marking  immediately as 1
Marking  fling as 1
Marking  the as 1
Marking  united as 1
Marking  states as 1
Marking  into as 1
Marking  a as 1
Marking  state as 1
Marking  of as 1
Marking  panic as 1
Marking  , as 1
Marking  and as 1
Marking  it as 1
Marking  ’s as 1
Marking  always as 1
Marking  good as 1
Marking  to as 1
Marking  be as 1
Marking  prepared as 1
Marking  just as 1
Marking  in as 1
Marking  case as 1
Marking  . as 1
Marking  her as 5
Marking  professor as 5
Marking  believed as 5
Marking  australia as 5
Marking  ' as 5
Marking  is as 5
Marking  not as 5
Marking  a as 5
Marking  country as 5
Marking  the as 5
Marking  professor as 5
Marking  incorrectly as 5
Marking  thought as 5
Marking  australia as 5
Marking  " as 5
Marking  is as 5
Marking  not as 5
Marking  a as 5
Marking  country as 5
Marking  continent as 13
Marking  ; as 13
Marking  not as 13
Marking  a as 13
Marking  country as 13
Marking  just as 16
Marking  so as 16
Marking  we as 16
Marking  're as 16
Marking  

Marking  and as 16
Marking  the as 16
Marking  jewish as 16
Marking  question as 16
Marking  and as 16
Marking  his as 16
Marking  position as 16
Marking  on as 16
Marking  that as 16
Marking  and as 16
Marking  so as 16
Marking  forth as 16
Marking  . as 16
Marking  virulently as 8
Marking  anti as 8
Marking  - as 8
Marking  semitic as 8
Marking  supporter as 3
Marking  of as 3
Marking  israel as 3
Marking  means as 3
Marking  farrakhan as 3
Marking  supporter as 3
Marking  . as 3
Marking  
 as 3
Marking  so as 5
Marking  seriously as 5
Marking  that as 5
Marking  j as 5
Marking  street as 5
Marking  ca as 5
Marking  n't as 5
Marking  decide as 5
Marking  a as 9
Marking  hitler as 9
Marking  - as 9
Marking  lover as 9
Marking  from as 14
Marking  bad as 14
Marking  to as 14
Marking  worse as 14
Marking  from as 14
Marking  bad as 14
Marking  to as 14
Marking  worse as 14
Marking  a as 5
Marking  lot as 5
Marking  of as 5
Marking  us as 5
Marking  can as 5
Marking  just as 5
Marking  s

Marking  time as 5
Marking  he as 5
Marking  will as 5
Marking  not as 5
Marking  be as 5
Marking  guilty as 5
Marking  of as 5
Marking  twisting as 5
Marking  scripture as 5
Marking  the as 5
Marking  way as 5
Marking  that as 5
Marking  satan as 5
Marking  twists as 5
Marking  scripture as 5
Marking  gun as 6
Marking  control as 6
Marking  is as 6
Marking  now as 6
Marking  truly as 6
Marking  impossible as 6
Marking  wannabe as 9
Marking  statist as 9
Marking  dictator as 9
Marking  and as 9
Marking  naive as 9
Marking  do as 9
Marking  - as 9
Marking  gooder as 9
Marking  the as 4
Marking  latter as 4
Marking  think as 4
Marking  that as 4
Marking  removing as 4
Marking  guns as 4
Marking  will as 4
Marking  suddenly as 4
Marking  force as 4
Marking  humanity as 4
Marking  to as 4
Marking  stop as 4
Marking  all as 4
Marking  animosity as 4
Marking  toward as 4
Marking  one as 4
Marking  another as 4
Marking  , as 4
Marking  hold as 4
Marking  hands as 4
Marking  , as 4
Marking  an

Marking  suspicious as 5
Marking  of as 5
Marking  the as 5
Marking  guardian as 5
Marking  claim as 5
Marking  the as 9
Marking  russiagate as 9
Marking  fairytale as 9
Marking  the as 5
Marking  story as 5
Marking  was as 5
Marking  weakly as 5
Marking  sourced as 5
Marking  and as 5
Marking  included as 5
Marking  some as 5
Marking  details as 5
Marking  that as 5
Marking  seemed as 5
Marking  unlikely as 5
Marking  to as 5
Marking  be as 5
Marking  true as 5
Marking  in as 5
Marking  sum as 5
Marking  , as 5
Marking  the as 5
Marking  guardian as 5
Marking  published as 5
Marking  a as 5
Marking  story as 5
Marking  today as 5
Marking  that as 5
Marking  it as 5
Marking  knew as 5
Marking  would as 5
Marking  explode as 5
Marking  into as 5
Marking  all as 5
Marking  sorts as 5
Marking  of as 5
Marking  viral as 5
Marking  benefits as 5
Marking  for as 5
Marking  the as 5
Marking  paper as 5
Marking  and as 5
Marking  its as 5
Marking  reporters as 5
Marking  even as 5
Marking  tho

Marking  the as 5
Marking  politico as 5
Marking  screed as 5
Marking  that as 5
Marking  supports as 5
Marking  its as 5
Marking  suggestions as 5
Marking  and as 5
Marking  claims as 5
Marking  . as 5
Marking  
 as 5
Marking  it as 5
Marking  is as 5
Marking  fake as 5
Marking  news as 5
Marking  about as 5
Marking  a as 5
Marking  fake as 5
Marking  news as 5
Marking  story as 5
Marking  fake as 13
Marking  news as 13
Marking  unfortunately as 5
Marking  no as 5
Marking  western as 5
Marking  main as 5
Marking  stream as 5
Marking  media as 5
Marking  can as 5
Marking  any as 5
Marking  longer as 5
Marking  be as 5
Marking  trusted as 5
Marking  to as 5
Marking  publish as 5
Marking  the as 5
Marking  truth as 5
Marking  unfortunately as 6
Marking  no as 6
Marking  western as 6
Marking  main as 6
Marking  stream as 6
Marking  media as 6
Marking  can as 6
Marking  any as 6
Marking  longer as 6
Marking  be as 6
Marking  trusted as 6
Marking  to as 6
Marking  publish as 6
Marking  the 

Marking  and as 8
Marking  undermining as 8
Marking  arch as 9
Marking  - as 9
Marking  conservative as 9
Marking  ” as 9
Marking  rottweiler as 9
Marking  ” as 9
Marking  benedict as 9
Marking  xvi as 9
Marking  progressive as 9
Marking  ” as 9
Marking  destroyer as 9
Marking  of as 9
Marking  ottaviani as 9
Marking  arch as 9
Marking  - as 9
Marking  conservative as 9
Marking  ” as 9
Marking  … as 9
Marking  a as 9
Marking  man as 9
Marking  called as 9
Marking  “ as 9
Marking  progressive as 9
Marking  ” as 9
Marking  progressive as 13
Marking  ” as 13
Marking  godfather as 9
Marking  of as 9
Marking  the as 9
Marking  “ as 9
Marking  liberal as 9
Marking  ” as 9
Marking  european as 9
Marking  catholic as 9
Marking  church as 9
Marking  , as 9
Marking  the as 9
Marking  “ as 9
Marking  godfather as 9
Marking  ” as 9
Marking  of as 9
Marking  the as 9
Marking  “ as 9
Marking  liberal as 9
Marking  wing as 9
Marking  ” as 9
Marking  of as 9
Marking  european as 9
Marking  catholicism

Marking  shock as 8
Marking  grossly as 8
Marking  disproportionate as 8
Marking  overzealous as 8
Marking  devoted as 9
Marking  family as 9
Marking  men as 9
Marking  respected as 9
Marking  contributors as 9
Marking  to as 9
Marking  their as 9
Marking  local as 9
Marking  community as 9
Marking  tyrants as 9
Marking  deep as 9
Marking  state as 9
Marking  insurrection as 9
Marking  deep as 9
Marking  state as 9
Marking  officials as 9
Marking  are as 8
Marking  in as 8
Marking  panic as 8
Marking  mode as 8
Marking  deep as 13
Marking  state as 13
Marking  deep as 9
Marking  state as 9
Marking  doj as 9
Marking  tool as 9
Marking  the as 7
Marking  us as 7
Marking  president as 7
Marking  wants as 7
Marking  every as 7
Marking  american as 7
Marking  citizen as 7
Marking  to as 7
Marking  see as 7
Marking  the as 7
Marking  full as 7
Marking  , as 7
Marking  unredacted as 7
Marking  version as 7
Marking  of as 7
Marking  the as 7
Marking  fisa as 7
Marking  documents as 7
Marking  

Marking  patel as 5
Marking  agreed as 5
Marking  to as 5
Marking  bring as 5
Marking  it as 5
Marking  by as 5
Marking  , as 5
Marking  but as 5
Marking  two as 5
Marking  days as 5
Marking  later as 5
Marking  he as 5
Marking  told as 5
Marking  the as 5
Marking  state as 5
Marking  department as 5
Marking  he as 5
Marking  had as 5
Marking  accidentally as 5
Marking  thrown as 5
Marking  it as 5
Marking  away as 5
Marking  in as 5
Marking  october as 5
Marking  and as 5
Marking  needed as 5
Marking  a as 5
Marking  new as 5
Marking  one as 5
Marking  blatant as 8
Marking  mi6 as 8
Marking  lies as 8
Marking  the as 5
Marking  right as 5
Marking  wing as 5
Marking  ecuadorean as 5
Marking  government as 5
Marking  of as 5
Marking  president as 5
Marking  moreno as 5
Marking  continues as 5
Marking  to as 5
Marking  churn as 5
Marking  out as 5
Marking  its as 5
Marking  production as 5
Marking  line as 5
Marking  of as 5
Marking  fake as 5
Marking  documents as 5
Marking  regarding a

Marking  at as 5
Marking  travis as 5
Marking  air as 5
Marking  force as 5
Marking  base as 5
Marking  allahu as 8
Marking  akbar as 8
Marking  of as 5
Marking  course as 5
Marking  , as 5
Marking  even as 5
Marking  if as 5
Marking  they as 5
Marking  had as 5
Marking  found as 5
Marking  those as 5
Marking  things as 5
Marking  , as 5
Marking  given as 5
Marking  their as 5
Marking  track as 5
Marking  record as 5
Marking  of as 5
Marking  denial as 5
Marking  and as 5
Marking  deception as 5
Marking  , as 5
Marking  they as 5
Marking  may as 5
Marking  still as 5
Marking  be as 5
Marking  searching as 5
Marking  for as 5
Marking  kazi as 5
Marking  ’s as 5
Marking  motive as 5
Marking  in as 1
Marking  any as 1
Marking  case as 1
Marking  , as 1
Marking  a as 1
Marking  larger as 1
Marking  point as 1
Marking  is as 1
Marking  being as 1
Marking  lost as 1
Marking  here as 1
Marking  . as 1
Marking  
 as 1
Marking  and as 1
Marking  that as 1
Marking  is as 1
Marking  that as 1
Mar

Marking  it as 5
Marking  had as 5
Marking  done as 5
Marking  so as 5
Marking  , as 5
Marking  to as 5
Marking  attribute as 5
Marking  the as 5
Marking  claims as 5
Marking  to as 5
Marking  unnamed as 5
Marking  , as 5
Marking  and as 5
Marking  uncheckable as 5
Marking  , as 5
Marking  “ as 5
Marking  sources as 5
Marking  the as 5
Marking  propaganda as 5
Marking  function as 5
Marking  of as 5
Marking  the as 5
Marking  piece as 5
Marking  is as 5
Marking  patent as 5
Marking  the as 5
Marking  guardian as 5
Marking  ’s as 5
Marking  latest as 5
Marking  story as 5
Marking  provides as 5
Marking  a as 5
Marking  supposedly as 5
Marking  stronger as 5
Marking  foundation as 5
Marking  for as 5
Marking  an as 5
Marking  existing as 5
Marking  narrative as 5
Marking  : as 5
Marking  that as 5
Marking  assange as 5
Marking  and as 5
Marking  wikileaks as 5
Marking  knowingly as 5
Marking  published as 5
Marking  emails as 5
Marking  hacked as 5
Marking  by as 5
Marking  russia as 5
M

Marking  symptom as 5
Marking  of as 5
Marking  a as 5
Marking  deeper as 5
Marking  malaise as 5
Marking  in as 5
Marking  the as 5
Marking  guardian as 5
Marking  and as 5
Marking  the as 5
Marking  wider as 5
Marking  corporate as 5
Marking  media as 5
Marking  a as 9
Marking  deeper as 9
Marking  malaise as 9
Marking  in as 9
Marking  the as 9
Marking  guardian as 9
Marking  and as 9
Marking  the as 9
Marking  wider as 9
Marking  corporate as 9
Marking  media as 9
Marking  even as 5
Marking  aside as 5
Marking  from as 5
Marking  its as 5
Marking  decade as 5
Marking  - as 5
Marking  long as 5
Marking  campaign as 5
Marking  against as 5
Marking  assange as 5
Marking  , as 5
Marking  the as 5
Marking  guardian as 5
Marking  is as 5
Marking  far as 5
Marking  from as 5
Marking  “ as 5
Marking  solid as 5
Marking  and as 5
Marking  reliable as 5
Marking  ” as 5
Marking  , as 5
Marking  as as 5
Marking  greenwald as 5
Marking  claims as 5
Marking  . as 5
Marking  
 as 5
Marking  it as

Marking  the as 4
Marking  existing as 4
Marking  , as 4
Marking  neoliberal as 4
Marking  order as 4
Marking  the as 9
Marking  existing as 9
Marking  , as 9
Marking  neoliberal as 9
Marking  order as 9
Marking  whistle as 8
Marking  - as 8
Marking  blowing as 8
Marking  a as 9
Marking  corrupt as 9
Marking  western as 9
Marking  elite as 9
Marking  the as 9
Marking  rapacious as 9
Marking  financial as 9
Marking  industries as 9
Marking  a as 9
Marking  damaging as 9
Marking  and as 9
Marking  exploitative as 9
Marking  us as 9
Marking  dominance as 9
Marking  of as 9
Marking  “ as 9
Marking  america as 9
Marking  ’s as 9
Marking  backyard as 9
Marking  the as 9
Marking  elite as 9
Marking  - as 9
Marking  friendly as 9
Marking  narratives as 9
Marking  of as 9
Marking  corporate as 9
Marking  media as 9
Marking  the as 4
Marking  guardian as 4
Marking  did as 4
Marking  not as 4
Marking  make as 4
Marking  a as 4
Marking  mistake as 4
Marking  in as 4
Marking  vilifying as 4
Marking

Marking  i as 5
Marking  did as 5
Marking  ! as 5
Marking  ” as 5
Marking  he as 5
Marking  wrote as 5
Marking  in as 0
Marking  his as 0
Marking  tweets as 0
Marking  , as 0
Marking  trump as 0
Marking  also as 0
Marking  quoted as 0
Marking  criticism as 0
Marking  of as 0
Marking  the as 0
Marking  investigation as 0
Marking  from as 0
Marking  alan as 0
Marking  dershowitz as 0
Marking  , as 0
Marking  a as 0
Marking  harvard as 0
Marking  law as 0
Marking  school as 0
Marking  professor as 0
Marking  who as 0
Marking  frequently as 0
Marking  defends as 0
Marking  trump as 0
Marking  on as 0
Marking  television as 0
Marking  . as 0
Marking  
 as 0
Marking  in as 0
Marking  an as 0
Marking  interview as 0
Marking  with as 0
Marking  the as 0
Marking  los as 0
Marking  angeles as 0
Marking  times as 0
Marking  , as 0
Marking  dershowitz as 0
Marking  said as 0
Marking  he as 0
Marking  does as 0
Marking  not as 0
Marking  believe as 0
Marking  sessions as 0
Marking  has as 0
Marking

Marking  completely as 3
Marking  the as 3
Marking  mode as 3
Marking  of as 3
Marking  christ as 3
Marking  ’s as 3
Marking  presence as 3
Marking  in as 3
Marking  this as 3
Marking  sacrament as 3
Marking  . as 3
Marking  

 as 3
Marking  nor as 3
Marking  is as 3
Marking  it as 3
Marking  allowable as 3
Marking  to as 3
Marking  discuss as 3
Marking  the as 3
Marking  mystery as 3
Marking  of as 3
Marking  transubstantiation as 3
Marking  without as 3
Marking  mentioning as 3
Marking  what as 3
Marking  the as 3
Marking  council as 3
Marking  of as 3
Marking  trent as 3
Marking  stated as 3
Marking  about as 3
Marking  the as 3
Marking  marvelous as 3
Marking  conversion as 3
Marking  of as 3
Marking  the as 3
Marking  whole as 3
Marking  substance as 3
Marking  of as 3
Marking  the as 3
Marking  bread as 3
Marking  into as 3
Marking  the as 3
Marking  body as 3
Marking  and as 3
Marking  of as 3
Marking  the as 3
Marking  whole as 3
Marking  substance as 3
Marking  of as 3
Marking

Marking  the as 1
Marking  chair as 1
Marking  of as 1
Marking  peter as 1
Marking  threatens as 1
Marking  the as 1
Marking  hierarchs as 1
Marking  with as 1
Marking  a as 1
Marking  legacy as 1
Marking  of as 1
Marking  shame as 1
Marking  and as 1
Marking  a as 1
Marking  terrible as 1
Marking  accountability as 1
Marking  before as 1
Marking  the as 1
Marking  just as 1
Marking  judge as 1
Marking  . as 1
Marking  the as 8
Marking  abuses as 8
Marking  of as 8
Marking  a as 8
Marking  tyrant as 8
Marking  on as 8
Marking  the as 8
Marking  chair as 8
Marking  of as 8
Marking  peter as 8
Marking  a as 9
Marking  tyrant as 9
Marking  on as 9
Marking  the as 9
Marking  chair as 9
Marking  of as 9
Marking  peter as 9
Marking  the as 16
Marking  time as 16
Marking  for as 16
Marking  “ as 16
Marking  prudence as 16
Marking  ” as 16
Marking  is as 16
Marking  long as 16
Marking  past as 16
Marking  . as 16
Marking  a as 8
Marking  papal as 8
Marking  tyranny as 8
Marking  the as 8
Marki

Marking  breaking as 8
Marking  fancy as 8
Marking  image as 8
Marking  - as 8
Marking  gathering as 8
Marking  hardware as 8
Marking  stunning as 8
Marking  gorgeously as 8
Marking  detailed as 8
Marking  eye as 8
Marking  candy as 8
Marking  a as 6
Marking  greatest as 6
Marking  distance as 6
Marking  from as 6
Marking  earth as 6
Marking  than as 6
Marking  any as 6
Marking  in as 6
Marking  the as 6
Marking  history as 6
Marking  of as 6
Marking  mankind as 6
Marking  yeah as 8
Marking  , as 8
Marking  it as 8
Marking  ’s as 8
Marking  kind as 8
Marking  of as 8
Marking  crazy as 8
Marking  yeah as 16
Marking  , as 16
Marking  it as 16
Marking  ’s as 16
Marking  kind as 16
Marking  of as 16
Marking  crazy as 16
Marking  fastest as 6
Marking  spacecraft as 6
Marking  ever as 6
Marking  launched as 6
Marking  farther as 6
Marking  from as 6
Marking  earth as 6
Marking  than as 6
Marking  any as 6
Marking  spacecraft as 6
Marking  in as 6
Marking  history as 6
Marking  outrage as 8
M

Marking  above as 0
Marking  the as 0
Marking  convenience as 0
Marking  of as 0
Marking  criminal as 0
Marking  aliens as 0
Marking  disgraceful as 8
Marking  verdict as 8
Marking  enjoyed as 6
Marking  all as 6
Marking  the as 6
Marking  rights as 6
Marking  of as 6
Marking  the as 6
Marking  american as 6
Marking  legal as 6
Marking  system as 6
Marking  , as 6
Marking  garcia as 1
Marking  zarate as 1
Marking  ’s as 1
Marking  background as 1
Marking  and as 1
Marking  nationality as 1
Marking  played as 1
Marking  a as 1
Marking  role as 1
Marking  in as 1
Marking  his as 1
Marking  prosecution as 1
Marking  . as 1
Marking  “ as 5
Marking  if as 5
Marking  this as 5
Marking  was as 5
Marking  a as 5
Marking  college as 5
Marking  student as 5
Marking  or as 5
Marking  swedish as 5
Marking  kid as 5
Marking  would as 5
Marking  he as 5
Marking  be as 5
Marking  charged as 5
Marking  with as 5
Marking  murder as 5
Marking  ? as 5
Marking  ” as 5
Marking  politically as 8
Marking  co

Marking  . as 8
Marking  

 as 8
Marking  disastrous as 8
Marking  depressing as 8
Marking  like as 8
Marking  a as 8
Marking  funeral as 8
Marking  bell as 8
Marking  most as 6
Marking  desperate as 6
Marking  still as 6
Marking  less as 6
Marking  downright as 8
Marking  bizarre as 8
Marking  controlled as 8
Marking  , as 8
Marking  systematized as 8
Marking  extinction as 8
Marking  incredible as 8
Marking  death as 8
Marking  throes as 8
Marking  impending as 8
Marking  total as 8
Marking  extinction as 8
Marking  what as 8
Marking  are as 8
Marking  these as 8
Marking  people as 8
Marking  smoking as 8
Marking  ? as 8
Marking  what as 5
Marking  are as 5
Marking  these as 5
Marking  people as 5
Marking  smoking as 5
Marking  ? as 5
Marking  
 as 5
Marking  new as 13
Marking  dawn’ as 13
Marking  demolition as 8
Marking  terrible as 8
Marking  christianity as 7
Marking  is as 7
Marking  europe as 7
Marking  ’s as 7
Marking  last as 7
Marking  hope’ as 7
Marking  christianity as 14


Marking  character as 14
Marking  assassination as 14
Marking  search as 9
Marking  and as 9
Marking  destroy as 9
Marking  strategy as 9
Marking  total as 8
Marking  sham as 8
Marking  the as 0
Marking  senate as 0
Marking  must as 0
Marking  vote as 0
Marking  kavanaugh as 8
Marking  stole as 8
Marking  the as 8
Marking  show as 8
Marking  trembled as 8
Marking  with as 8
Marking  righteous as 8
Marking  indignation as 8
Marking  and as 13
Marking  then as 13
Marking  last as 8
Marking  - as 8
Marking  minute as 8
Marking  smears as 8
Marking  afraid as 8
Marking  of as 8
Marking  their as 8
Marking  own as 8
Marking  shadows as 8
Marking  all as 9
Marking  - as 9
Marking  male as 9
Marking  team as 9
Marking  ridiculous as 8
Marking  overall as 8
Marking  story as 8
Marking  “ as 5
Marking  hard as 5
Marking  to as 5
Marking  do as 5
Marking  much as 5
Marking  else as 5
Marking  when as 5
Marking  the as 5
Marking  witness as 5
Marking  conveniently as 5
Marking  has as 5
Marking  

Marking  kavanaugh as 9
Marking  worse as 6
Marking  than as 6
Marking  a as 6
Marking  travesty as 6
Marking  character as 14
Marking  assassination as 14
Marking  bent as 8
Marking  over as 8
Marking  backwards as 8
Marking  ready as 8
Marking  to as 8
Marking  pounce as 8
Marking  character as 13
Marking  assassination as 13
Marking  character as 14
Marking  assassination as 14
Marking  continue as 8
Marking  to as 8
Marking  bludgeon as 8
Marking  what as 5
Marking  we as 5
Marking  do as 5
Marking  know as 5
Marking  so as 5
Marking  far as 5
Marking  tends as 5
Marking  to as 5
Marking  undercut as 5
Marking  the as 5
Marking  credibility as 5
Marking  of as 5
Marking  ms. as 5
Marking  ford as 5
Marking  ’s as 5
Marking  accusation as 5
Marking  whatever as 5
Marking  corroboration as 5
Marking  ms. as 5
Marking  ford as 5
Marking  was as 5
Marking  hoping as 5
Marking  for as 5
Marking  from as 5
Marking  “ as 5
Marking  witnesses as 5
Marking  ” as 5
Marking  she as 5
Marking 

Marking  delighted as 8
Marking  screams as 8
Marking  of as 8
Marking  “ as 8
Marking  allahu as 8
Marking  akbar as 8
Marking  the as 6
Marking  “ as 6
Marking  establishment as 6
Marking  of as 6
Marking  an as 6
Marking  islamic as 6
Marking  state as 6
Marking  … as 6
Marking  requires as 6
Marking  the as 6
Marking  conquest as 6
Marking  of as 6
Marking  america as 6
Marking  , as 6
Marking  britain as 6
Marking  , as 6
Marking  russia as 6
Marking  , as 6
Marking  france as 6
Marking  , as 6
Marking  and as 6
Marking  italy as 6
Marking  – as 6
Marking  rome as 6
Marking  and as 6
Marking  other as 6
Marking  infidel as 6
Marking  lands as 6
Marking  will as 6
Marking  be as 6
Marking  conquered as 6
Marking  the as 7
Marking  “ as 7
Marking  establishment as 7
Marking  of as 7
Marking  an as 7
Marking  islamic as 7
Marking  state as 7
Marking  … as 7
Marking  requires as 7
Marking  the as 7
Marking  conquest as 7
Marking  of as 7
Marking  america as 7
Marking  , as 7
Marking  

Marking  pain as 8
Marking  had as 8
Marking  apologised as 8
Marking  - as 8
Marking  except as 8
Marking  - as 8
Marking  not as 8
Marking  - as 8
Marking  really as 8
Marking  the as 5
Marking  accusations as 5
Marking  are as 5
Marking  , as 5
Marking  after as 5
Marking  all as 5
Marking  , as 5
Marking  still as 5
Marking  lies as 5
Marking  , as 5
Marking  and as 5
Marking  that as 5
Marking  there as 5
Marking  ’s as 5
Marking  still as 5
Marking  “ as 5
Marking  no as 5
Marking  evidence as 5
Marking  ” as 5
Marking  against as 5
Marking  barros as 5
Marking  … as 5
Marking  ? as 5
Marking  dropped as 8
Marking  the as 8
Marking  bomb as 8
Marking  it as 5
Marking  also as 5
Marking  calls as 5
Marking  into as 5
Marking  question as 5
Marking  his as 5
Marking  stated as 5
Marking  empathy as 5
Marking  with as 5
Marking  abuse as 5
Marking  survivors as 5
Marking  , as 5
Marking  i as 0
Marking  am as 0
Marking  the as 0
Marking  pope as 0
Marking  , as 0
Marking  i as 0
Mar

Marking  to as 4
Marking  protect as 4
Marking  national as 4
Marking  security as 4
Marking  and as 4
Marking  elevate as 4
Marking  johnson as 4
Marking  , as 4
Marking  who as 4
Marking  had as 4
Marking  the as 4
Marking  same as 4
Marking  anti as 4
Marking  - as 4
Marking  communist as 4
Marking  mindset as 4
Marking  as as 4
Marking  the as 4
Marking  pentagon as 4
Marking  and as 4
Marking  the as 4
Marking  cia as 4
Marking  , as 4
Marking  to as 4
Marking  the as 4
Marking  presidency as 4
Marking  . as 4
Marking  no as 4
Marking  doubt as 4
Marking  being as 4
Marking  told as 4
Marking  that as 4
Marking  he as 4
Marking  was as 4
Marking  being as 4
Marking  prepared as 4
Marking  for as 4
Marking  an as 4
Marking  important as 4
Marking  mission as 4
Marking  , as 4
Marking  no as 16
Marking  government as 16
Marking  operation as 16
Marking  ever as 16
Marking  goes as 16
Marking  perfectly as 16
Marking  . as 16
Marking  dreadfully as 8
Marking  wrong as 8
Marking  shro

Marking  alleged as 9
Marking  muslim as 9
Marking  spies as 9
Marking  pakistani as 9
Marking  - as 9
Marking  born as 9
Marking  aides as 9
Marking  muslim as 13
Marking  spy as 13
Marking  muslim as 9
Marking  spy as 9
Marking  ring as 9
Marking  tried as 8
Marking  to as 8
Marking  squirrel as 8
Marking  jihad as 9
Marking  spies as 9
Marking  congress as 1
Marking  must as 1
Marking  investigate as 1
Marking  and as 1
Marking  act as 1
Marking  lashed as 8
Marking  out as 8
Marking  at as 8
Marking  her as 8
Marking  you as 9
Marking  ’re as 9
Marking  a as 9
Marking  liar as 9
Marking  you as 5
Marking  ’re as 5
Marking  a as 5
Marking  liar as 5
Marking  , as 5
Marking  are as 5
Marking  n’t as 5
Marking  you as 5
Marking  ma’am as 5
Marking  , as 5
Marking  you as 5
Marking  lied as 5
Marking  to as 5
Marking  me as 5
Marking  , as 5
Marking  did as 5
Marking  n’t as 5
Marking  you as 5
Marking  you as 5
Marking  lied as 5
Marking  to as 5
Marking  me as 5
Marking  , as 5
Marki

Marking  - as 9
Marking  class as 9
Marking  islamopanderer as 9
Marking  ? as 5
Marking  
 as 5
Marking  the as 5
Marking  catholic as 5
Marking  church as 5
Marking  is as 5
Marking  following as 5
Marking  pope as 5
Marking  francis’ as 5
Marking  lead as 5
Marking  , as 5
Marking  and as 5
Marking  francis as 5
Marking  has as 5
Marking  said as 5
Marking  : as 5
Marking  “ as 5
Marking  christian as 5
Marking  terrorism as 5
Marking  does as 5
Marking  not as 5
Marking  exist as 5
Marking  , as 5
Marking  jewish as 5
Marking  terrorism as 5
Marking  does as 5
Marking  not as 5
Marking  exist as 5
Marking  , as 5
Marking  and as 5
Marking  muslim as 5
Marking  terrorism as 5
Marking  does as 5
Marking  not as 5
Marking  exist as 5
Marking  . as 5
Marking  
 as 5
Marking  they as 5
Marking  do as 5
Marking  not as 5
Marking  exist as 5
Marking  . as 5
Marking  ” as 5
Marking  and as 5
Marking  he as 5
Marking  has as 5
Marking  also as 5
Marking  said as 5
Marking  : as 5
Marking  “

Marking  , as 5
Marking  the as 5
Marking  fbi as 5
Marking  insists as 5
Marking  there as 5
Marking  is as 5
Marking  no as 5
Marking  jihad as 5
Marking  motive as 5
Marking  , as 5
Marking  while as 5
Marking  saying as 5
Marking  they as 5
Marking  do as 5
Marking  n’t as 5
Marking  know as 5
Marking  his as 5
Marking  motive as 5
Marking  that as 5
Marking  raised as 5
Marking  a as 5
Marking  number as 5
Marking  of as 5
Marking  question as 5
Marking  contradicting as 5
Marking  a as 5
Marking  timeline as 5
Marking  they as 5
Marking  had as 5
Marking  offered as 5
Marking  earlier as 5
Marking  this as 5
Marking  week as 5
Marking  … as 5
Marking  . as 5
Marking  these as 5
Marking  discrepancies as 5
Marking  on as 5
Marking  basic as 5
Marking  facts as 5
Marking  are as 5
Marking  feeding as 5
Marking  conspiracy as 5
Marking  theories as 5
Marking  . as 5
Marking  freaking as 8
Marking  out as 8
Marking  “ as 9
Marking  good as 9
Marking  tobin as 9
Marking  ” as 9
Markin

Marking  gratuitously as 8
Marking  abused as 8
Marking  a as 9
Marking  “ as 9
Marking  damaged as 9
Marking  personality as 9
Marking  ” as 9
Marking  and as 9
Marking  “ as 9
Marking  callous as 9
Marking  gloated as 8
Marking  on as 8
Marking  his as 8
Marking  blog as 8
Marking  bogus as 8
Marking  and as 8
Marking  farcical as 8
Marking  trying as 8
Marking  to as 8
Marking  clamp as 8
Marking  down as 8
Marking  audaciously as 8
Marking  revealed as 8
Marking  with as 8
Marking  their as 8
Marking  attendant as 8
Marking  rape as 8
Marking  , as 8
Marking  murder as 8
Marking  and as 8
Marking  destruction as 8
Marking  the as 4
Marking  authorities as 4
Marking  care as 4
Marking  so as 4
Marking  little as 4
Marking  about as 4
Marking  violence as 4
Marking  against as 4
Marking  women as 4
Marking  that as 4
Marking  they as 4
Marking  manipulate as 4
Marking  rape as 4
Marking  allegations as 4
Marking  at as 4
Marking  will as 4
Marking  a as 8
Marking  media as 8
Marking 

Marking  muslims as 6
Marking  to as 4
Marking  eradicate as 4
Marking  these as 4
Marking  , as 4
Marking  muslims as 4
Marking  are as 4
Marking  required as 4
Marking  to as 4
Marking  wage as 4
Marking  war as 4
Marking  until as 4
Marking  there as 4
Marking  exists as 4
Marking  none as 4
Marking  of as 4
Marking  it as 4
Marking  in as 4
Marking  the as 4
Marking  world as 4
Marking  , as 4
Marking  and as 4
Marking  the as 4
Marking  only as 4
Marking  religion as 4
Marking  is as 4
Marking  that as 4
Marking  of as 4
Marking  allah as 4
Marking  wills as 5
Marking  does as 5
Marking  n’t as 5
Marking  mention as 5
Marking  the as 5
Marking  existence as 5
Marking  of as 5
Marking  such as 5
Marking  interpretations as 5
Marking  , as 5
Marking  even as 5
Marking  to as 5
Marking  dismiss as 5
Marking  them as 5
Marking  likewise as 5
Marking  , as 5
Marking  when as 5
Marking  he as 5
Marking  claims as 5
Marking  that as 5
Marking  the as 5
Marking  qur’an as 5
Marking  has a

INFO:root:Dataset Created


them as 5
Marking  and as 5
Marking  why as 5
Marking  because as 4
Marking  they as 4
Marking  have as 4
Marking  simply as 4
Marking  forsaken as 4
Marking  the as 4
Marking  cross as 4
Marking  they as 9
Marking  are as 9
Marking  people as 9
Marking  pleasers as 9
Marking  and as 9
Marking  nothing as 9
Marking  more as 9
Marking  hide as 8
Marking  behind as 8
Marking  a as 8
Marking  microphone as 8
Marking  the as 4
Marking  reason as 4
Marking  they as 4
Marking  do as 4
Marking  n't as 4
Marking  is as 4
Marking  because as 4
Marking  they as 4
Marking  are as 4
Marking  guilty as 4
Marking  of as 4
Marking  what as 4
Marking  they as 4
Marking  fail as 4
Marking  to as 4
Marking  confront as 4
Marking  paper as 9
Marking  tigers as 9
Marking  they as 5
Marking  can as 5
Marking  write as 5
Marking  all as 5
Marking  big as 5
Marking  and as 5
Marking  bad as 5
Marking  but as 5
Marking  when as 5
Marking  it as 5
Marking  comes as 5
Marking  to as 5
Marking  what as 5
Marking

In [6]:
dev_dir = pathlib.Path('/data/fakenews/tasks-2-3/dev/')
ids_dev, texts_dev, labels_dev = read_data(dev_dir)
dev = PropagandaDataset(ids_dev, texts_dev, labels_dev, vocab)

In [7]:
db = DataBunch(DataLoader(train, batch_size=3, shuffle=True), DataLoader(valid,batch_size=4),
               collate_fn=partial(pad_collate_concat, pad_idx=1))
logging.info("Databunch Created")

INFO:root:Databunch Created


In [8]:
vocab_sz = len(vocab.itos)
emb_sz = 400
n_hid = 400
n_layers = 3
pad_token = 1
model = SequentialRNN(MultiBatchRNNCore(120, 9135, vocab_sz, emb_sz, n_hid, n_layers, pad_token, bidir=True),
                      MultiLinearDecoder(len(PROPAGANDA_TYPES), 2, emb_sz, 0.15))

In [9]:
weights = torch.load('/data/fakenews/lstm_wt103.pth')
weights_emb = {
    'encoder.weight': weights['0.encoder.weight'],
    'encoder_dp.emb.weight': weights['0.encoder_dp.emb.weight']
}

In [10]:
from metrics import recall
callbacks = [accuracy ] + [recall(i) for i in range(18)]
learner = RNNLearner(db, model, loss_func=annotation_loss,metrics=callbacks, split_func=rnn_classifier_split )
#learner.load_encoder('/data/fakenews/lstm_wt103_enc')

In [11]:
learner.model[0].load_state_dict(weights_emb, strict=False)


In [38]:
learner.lr_find()
learner.recorder.plot()

LR Finder is complete, type {learner_name}.recorder.plot() to see the graph.


RuntimeError: CUDA out of memory. Tried to allocate 41.88 MiB (GPU 0; 5.94 GiB total capacity; 4.13 GiB already allocated; 33.06 MiB free; 714.36 MiB cached)

In [12]:
learner.fit_one_cycle(3, slice(1e-2))

In [13]:
learner.fit_one_cycle(3, slice(1e-2))

In [14]:
learner.fit_one_cycle(5, slice(1e-2))

In [15]:
learner.save('bigger-vl-0.279')

In [16]:
learner.fit_one_cycle(10, slice(1e-2))

In [11]:
learner.save('bigger-train_loss-0.205')

In [34]:
learner.fit_one_cycle(10, slice(1e-2))

In [18]:
def pred(ds, idx):
    model.eval()
    preds = model(torch.LongTensor(ds[idx][0]).unsqueeze(0).cuda())[0][0]
    labels = preds.argmax(-1)
    return preds, labels
    

In [19]:
scores = []
for i in range(len(dev)):
    preds,labels = pred(dev, i)
    scores.append(labels)
    if (labels > 0).nonzero().sum() > 0:
        print(i)
        nz = (labels>0).nonzero()
        print( nz)
        print(dev.tokens[i][nz[0,0] -5:nz[0,0]+5])
        print(dev.tokens[i][nz[0,0]])
        

0
tensor([[   5,    8],
        [  23,    8],
        [  24,    8],
        ...,
        [1824,    8],
        [1826,    8],
        [1827,    8]], device='cuda:0')
['9', 'steps', 'to', 'successfully', 'counter', 'jihad', '\n\n', '[', 'pre', '-']
jihad
1
tensor([[  28,    5],
        [  29,    5],
        [  30,    1],
        ...,
        [2413,    5],
        [2414,    5],
        [2415,    5]], device='cuda:0')
['catholic', 'spirit', ')', ':', '\n', 'every', 'time', 'mass', 'is', 'celebrated']
every
2
tensor([[  7,   8],
        [  7,   9],
        [ 24,   8],
        ...,
        [782,   9],
        [783,   8],
        [783,   9]], device='cuda:0')
['video', ':', 'gillum', 'staffer', 'makes', 'racist', 'statements', 'and', 'admits', 'campaign']
racist
3
tensor([[  1,   8],
        [  2,   8],
        [  2,   9],
        [  3,   8],
        [  3,   9],
        [ 56,   5],
        [ 57,   5],
        [ 59,   5],
        [ 60,   5],
        [137,   8],
        [138,   8],
        [138

6
tensor([[  0,   7],
        [  0,   8],
        [  0,  14],
        [  2,   8],
        [  3,   8],
        [ 21,   8],
        [ 23,   8],
        [ 23,   9],
        [ 24,   8],
        [ 24,   9],
        [ 25,   8],
        [ 25,   9],
        [ 40,   8],
        [ 41,   8],
        [ 93,   8],
        [ 94,   8],
        [ 95,   8],
        [ 96,   8],
        [ 97,   8],
        [110,   8],
        [110,   9],
        [111,   8],
        [111,   9],
        [112,   6],
        [112,   8],
        [112,   9],
        [113,   6],
        [113,   8],
        [113,   9],
        [114,   8],
        [114,   9],
        [115,   8],
        [117,   5],
        [179,   8],
        [180,   8],
        [183,   8],
        [233,   5],
        [234,   5],
        [248,   8],
        [270,   8],
        [276,   8],
        [312,   5],
        [313,   5],
        [314,   5],
        [315,   5],
        [316,   5],
        [317,   5],
        [318,   5],
        [319,   5],
        [320,   5]

9
tensor([[ 74,   8],
        [ 75,   8],
        [ 92,   5],
        [ 95,   5],
        [ 96,   5],
        [201,   8],
        [202,   8],
        [202,   9],
        [214,   8],
        [215,   8],
        [215,   9],
        [227,   8],
        [228,   8],
        [228,   9],
        [338,   8],
        [375,   5],
        [376,   5],
        [377,   5],
        [379,   5],
        [380,   5],
        [381,   5],
        [382,   5],
        [382,   8],
        [383,   5],
        [383,   6],
        [383,   8],
        [384,   5],
        [384,   6],
        [384,   8],
        [385,   5],
        [385,   6],
        [385,   8],
        [385,   9],
        [386,   5],
        [386,   6],
        [386,   8],
        [386,   9],
        [387,   5],
        [387,   6],
        [387,   8],
        [388,   5],
        [389,   5],
        [390,   5],
        [391,   5],
        [392,   5],
        [393,   5],
        [448,   5],
        [450,   5],
        [540,   8],
        [542,   8]

13
tensor([[  0,   8],
        [  1,   8],
        [  1,   9],
        ...,
        [799,   9],
        [800,   8],
        [800,   9]], device='cuda:0')
[]
keith
14
tensor([[ 22,   8],
        [ 22,   9],
        [ 23,   8],
        [ 23,   9],
        [ 24,   6],
        [ 24,   8],
        [ 24,   9],
        [ 24,  13],
        [ 25,   8],
        [ 25,   9],
        [ 26,   8],
        [ 26,   9],
        [ 27,   8],
        [ 27,   9],
        [ 28,   8],
        [ 28,   9],
        [ 29,   8],
        [ 39,   8],
        [103,   8],
        [110,   8],
        [111,   8],
        [112,   8],
        [168,   8],
        [169,   6],
        [169,   8],
        [169,   9],
        [170,   5],
        [170,   8],
        [170,   9],
        [171,   5],
        [171,   8],
        [172,   5],
        [173,   5],
        [174,   5],
        [175,   8],
        [176,   8],
        [183,   8],
        [183,   9],
        [184,   8],
        [215,   8],
        [215,   9],
        [396, 

19
tensor([[154,   8],
        [155,   8],
        [155,   9],
        [156,   8],
        [156,   9],
        [157,   6],
        [157,   8],
        [157,   9],
        [157,  13],
        [158,   8],
        [159,   8],
        [183,   8],
        [292,   8],
        [328,   8],
        [328,   9],
        [341,   8],
        [351,   8],
        [351,   9],
        [352,   8],
        [352,   9],
        [353,   8],
        [353,   9],
        [354,   8],
        [354,   9],
        [355,   8],
        [355,   9],
        [359,   8],
        [375,   8],
        [455,   8],
        [455,   9],
        [456,   8],
        [457,   8],
        [458,   8],
        [458,  14],
        [459,   6],
        [459,   8],
        [459,  13],
        [459,  14],
        [460,   6],
        [460,   8],
        [460,  13],
        [460,  14],
        [640,   5],
        [641,   5],
        [642,   5],
        [643,   5],
        [644,   4],
        [644,   5],
        [645,   4],
        [645,   5

27
tensor([[  0,   1],
        [  0,   5],
        [  0,   7],
        [  0,   8],
        [  0,  14],
        [  1,   1],
        [  1,   5],
        [  1,   7],
        [  1,   8],
        [  2,   1],
        [  2,   5],
        [  2,   7],
        [  2,   8],
        [  3,   1],
        [  3,   5],
        [  3,   7],
        [  3,   8],
        [  4,   5],
        [  5,   1],
        [  5,   5],
        [  6,   1],
        [  6,   5],
        [  7,   1],
        [  7,   5],
        [  7,   8],
        [  8,   1],
        [  8,   4],
        [  8,   5],
        [  9,   1],
        [  9,   4],
        [  9,   5],
        [ 10,   1],
        [ 10,   4],
        [ 10,   5],
        [ 11,   1],
        [ 11,   5],
        [ 12,   1],
        [ 12,   4],
        [ 12,   5],
        [ 13,   1],
        [ 13,   4],
        [ 13,   5],
        [ 13,   8],
        [ 14,   1],
        [ 14,   5],
        [ 15,   1],
        [ 15,   5],
        [ 16,   1],
        [ 16,   5],
        [ 16,   6

30
tensor([[  1,   8],
        [  1,   9],
        [ 37,   9],
        [ 38,   8],
        [ 38,   9],
        [ 39,   8],
        [ 39,   9],
        [ 40,   9],
        [ 46,   8],
        [ 47,   8],
        [ 48,   8],
        [ 49,   8],
        [ 65,   8],
        [ 69,   8],
        [117,   8],
        [118,   8],
        [119,   8],
        [126,   9],
        [171,   8],
        [172,   8],
        [172,   9],
        [184,   8],
        [185,   8],
        [185,   9],
        [197,   8],
        [198,   8],
        [198,   9],
        [319,   8],
        [320,   8],
        [365,   8],
        [365,   9],
        [372,   8],
        [375,   8],
        [386,   5],
        [387,   5],
        [389,   5],
        [389,   8],
        [390,   5],
        [392,   8],
        [393,   5],
        [393,   6],
        [393,   8],
        [394,   5],
        [394,   8],
        [396,   5],
        [397,   5],
        [398,   5],
        [399,   5],
        [400,   5],
        [401,   5

33
tensor([[ 35,   8],
        [ 36,   8],
        [ 47,   8],
        ...,
        [841,   8],
        [842,   8],
        [843,   8]], device='cuda:0')
['gillum', 'may', 'have', 'just', 'been', 'completely', 'undercut', 'by', 'a', 'member']
completely
34
tensor([[ 10,   8],
        [ 11,   8],
        [ 11,   9],
        [ 12,   8],
        [ 12,   9],
        [ 13,   8],
        [ 30,   8],
        [ 30,   9],
        [ 31,   8],
        [ 31,   9],
        [ 32,   6],
        [ 32,   8],
        [ 32,   9],
        [ 33,   8],
        [ 33,   9],
        [ 34,   5],
        [ 35,   5],
        [ 36,   5],
        [ 37,   5],
        [ 38,   5],
        [ 38,   8],
        [ 39,   5],
        [ 39,   8],
        [ 40,   5],
        [ 40,   6],
        [ 40,   8],
        [ 40,   9],
        [ 41,   5],
        [ 41,   6],
        [ 41,   8],
        [ 41,   9],
        [ 42,   8],
        [ 43,   8],
        [ 43,   9],
        [ 44,   8],
        [ 44,   9],
        [ 45,   8],
   

39
tensor([[   0,    1],
        [   0,    5],
        [   0,    6],
        ...,
        [2606,    4],
        [2606,    5],
        [2607,    5]], device='cuda:0')
[]
uranium
40
tensor([[ 12,   8],
        [ 12,   9],
        [ 13,   8],
        ...,
        [857,   8],
        [858,   6],
        [858,   8]], device='cuda:0')
[',', 'two', 'muslim', 'women', ',', 'rashida', 'tlaib', 'in', 'michigan', 'and']
rashida
41
tensor([[  8,   8],
        [  8,   9],
        [ 26,   8],
        ...,
        [652,   1],
        [652,   5],
        [652,   8]], device='cuda:0')
['parents', 'seethe', 'over', 'liberal', 'social', 'engineering', 'and', 'violence', '\n\n', 'homeschooling']
engineering
42
tensor([[ 41,   8],
        [ 46,   9],
        [181,   8],
        [218,   8]], device='cuda:0')
['home', 'country', 'on', 'charges', 'of', 'homicide', '.', '\n', 'rigoberto', 'gonzalez']
homicide
43
tensor([[  0,   8],
        [  0,   9],
        [  1,   8],
        [  1,   9],
        [  2,   8],

47
tensor([[ 53,   5],
        [ 54,   5],
        [ 55,   5],
        ...,
        [568,   6],
        [568,   8],
        [568,   9]], device='cuda:0')
['for', 'senate', ':', '“', 'as', 'an', 'individual', ',', 'if', 'i']
an
48
tensor([[  1,   8],
        [155,   8],
        [320,   8],
        [320,   9],
        [321,   8],
        [321,   9],
        [322,   8],
        [322,   9],
        [324,   8],
        [324,   9],
        [325,   8],
        [325,   9],
        [326,   8],
        [326,   9],
        [327,   9],
        [328,   9],
        [375,   9],
        [378,   8],
        [455,   9],
        [458,   8],
        [524,   8],
        [524,   9],
        [525,   8],
        [525,   9],
        [526,   8],
        [526,   9],
        [527,   8],
        [528,   8],
        [600,   8],
        [601,   8],
        [602,   8],
        [603,   8],
        [663,   8],
        [668,   8],
        [669,   8],
        [701,   8],
        [702,   8],
        [703,   8],
        [7

50
tensor([[   1,    8],
        [   1,    9],
        [   2,    8],
        ...,
        [1452,    9],
        [1453,    8],
        [1462,    8]], device='cuda:0')
[]
lifts
51
tensor([[   3,    8],
        [   3,    9],
        [   4,    8],
        ...,
        [3939,    5],
        [3940,    5],
        [3941,    5]], device='cuda:0')
[]
‘
52
tensor([[  0,   8],
        [  0,   9],
        [  4,   8],
        [  5,   8],
        [  5,   9],
        [  6,   8],
        [  6,   9],
        [  7,   8],
        [  7,   9],
        [  8,   8],
        [  8,   9],
        [  9,   8],
        [  9,   9],
        [ 55,   8],
        [ 55,   9],
        [ 93,   8],
        [ 96,   8],
        [142,   8]], device='cuda:0')
[]
sanctuary
53
tensor([[   0,    8],
        [   1,    8],
        [   2,    8],
        [   2,    9],
        [   3,    8],
        [   4,    8],
        [  41,    8],
        [  42,    8],
        [  43,    8],
        [  48,    8],
        [  50,    8],
        [  82, 

56
tensor([[   0,    8],
        [   5,    5],
        [   6,    5],
        ...,
        [1307,    8],
        [1308,    5],
        [1319,    8]], device='cuda:0')
[]
muslim


In [20]:
from output import output_preds, output_single
res_df = output_preds(dev, scores)

In [21]:
res_df['propaganda'].value_counts()

Loaded_Language                1673
Name_Calling,Labeling           890
Doubt                           846
Exaggeration,Minimisation       601
Appeal_to_fear-prejudice        437
Flag-Waving                     421
Causal_Oversimplification       398
Black-and-White_Fallacy         183
Repetition                      132
Slogans                         121
Thought-terminating_Cliches      44
Appeal_to_Authority              43
Reductio_ad_hitlerum             34
Name: propaganda, dtype: int64

In [22]:
res_df.to_csv('/tmp/dev6.csv', sep='\t', columns=['id', 'propaganda', 'start','end'], header=False,index=False)

In [56]:
!subl /tmp/dev.csv
